FROM rust:1.90

# Install protoc and build tools
RUN apt-get update && \
    apt-get install -y protobuf-compiler pkg-config libssl-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["cargo", "run"]
